services:
  blog:
    container_name: blog-front
    build:
      context: .
    ports:
      - 80:8080
    environment:
      - DB_HOST=postgree
      - DB_DATABASE=db_dados
      - DB_USERNAME=root
      - DB_PASSWORD=admin
    restart: always
    depends_on:
      - postgree
    networks:
      - news_network

  postgree:
    image: postgres:16.3-alpine3.20
    labels:
      - name=db_dados
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db_dados
    networks:
      - news_network

volumes:
  db_dados:

networks:
  news_network:
    driver: bridge
