services:
  blog:
    container_name: blog-front
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - DB_HOST=${HOST_DB}
      - DB_DATABASE=${NAME_DB}
      - DB_USERNAME=${USERNAME_DB}
      - DB_PASSWORD=${PASSWORD_DB}
    restart: always
    depends_on:
      - postgree
    networks:
      - news_network

  postgree:
    image: postgres:16.3-alpine3.20
    labels:
      - name=db_dados
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${NAME_DB}
      - POSTGRES_USER=${USERNAME_DB}
      - POSTGRES_PASSWORD=${PASSWORD_DB}
    networks:
      - news_network

volumes:
  db_dados:

networks:
  news_network:
    driver: bridge
